apiVersion: v1
kind: Service
metadata:
  name: story-service
spec: 
  selector:
    app: story
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 3000
  externalIPs:
    - 192.168.49.2
  type: NodePort